server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - uri: lb://MICROSERVICE
          predicates:
            - Path=/read*
        - uri: lb://MICROSERVICE2
          predicates:
            - Path=/add*, /update*, /delete*


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka